import random

# Define a list of possible user inputs and their corresponding responses
input_responses = {
    "hello": ["Hi there! Welcome to City University", "Hello! Welcome to City University", "Hey! Welcome to City University"],
    "hi": ["Hi there! Welcome to City University", "Hey! Welcome to City University"],
    "hey": ["Hello! Welcome to City University", "Hey! Welcome to City University"],
    "how are you": ["I'm doing well, thanks for asking.", "I'm good, how about you?", "I'm great, thanks!"],
    "how are you doing": ["I'm doing well, thanks for asking.", "I'm good, how about you?", "I'm great, thanks!"],
    "what's your name": ["My name is ChatBot.", "I go by ChatBot.", "You can call me ChatBot."],
    "your name": ["My name is ChatBot.", "I go by ChatBot."],
    "name": ["My name is ChatBot.", "You can call me ChatBot."],
    "what do you do": ["I'm here to help answer your questions!", "I'm a chatbot designed to assist you.", "I'm programmed to answer your queries."],
    "what is your work": ["I'm here to help answer your questions!", "I'm a chatbot designed to assist you.", "I'm programmed to answer your queries."],
    "what courses are offered": ["We offer a variety of courses. Please check our website for details."],
    "good morning": ["Good Morning!"],
    "good evening": ["Good Evening!"],
    "good afternoon": ["Good Afternoon!"],
    "i want to know about available course": ["You can check out our website for information on available courses and programs."],
    "what are the available courses": ["You can check out our website for information on available courses and programs."],
    "what are the available programs": ["You can check out our website for information on available courses and programs."],
    "what are the programs you offer": ["You can check out our website for information on available courses and programs."], 
    "what programs you offer": ["You can check out our website for information on available courses and programs."],
    "what course you offer": ["You can check out our website for information on available courses and programs."],
    "what are the admission requirements": ["The admission requirements vary depending on the program. Please check our website for more information."],
    "i want to know about admission requirements": ["The admission requirements vary depending on the program. Please check our website for more information."],
    "admission requirement details": ["The admission requirements vary depending on the program. Please check our website for more information."],
    "how can i apply for admission": ["You can apply for admission through our website by submitting admission form"],
    "how to apply for admission": ["You can apply for admission through our website by submitting admission form"],
    "what is the deadline for admission": ["The application deadline varies depending on the program. Please check our website for more information."],
    "admission deadline": ["The application deadline varies depending on the program. Please check our website for more information."],
    "what is the tuition fee": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Computer Science": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Electrical Engineering": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for BS English": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Management Sciences": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Health Sciences": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Mathematics": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Civil Engineering": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the tuition fee for Social Sciences": ["The tuition fee depend upon the programs. Please check our website for more information"],
    "what is the address of university": ["Our University is located at Dalazak Road, Peshawar"],
    "where the univerity is located": ["Our University is located at Dalazak Road, Peshawar"],
    "what is the location of the university": ["Our University is located at Dalazak Road, Peshawar"],
    "location of the university": ["Our University is located at Dalazak Road, Peshawar"],
    "what facilities the university offers": ["Our university offers a range of facilities including a library, cafeteria, labs and on-campus housing. Please check our website for more information."],
    "what are the university facilities":  ["Our university offers a range of facilities including a library, cafeteria, labs and on-campus housing. Please check our website for more information."],
   "what is the phone number": ["You can reach us at  +92 91 2609501-8."],
    "what is the contact number": ["You can reach us at  +92 91 2609501-8."],
   "contact number": ["You can reach us at  +92 91 2609501-8."],
    "what is the contact email": ["You can email us at info@cusit.edu.pk"],
    "what is the email address": ["You can email us at info@cusit.edu.pk"],
   "what are the admission requirements for undergraduate programs?": ["The admission requirements for undergraduate programs vary depending on the specific program. Generally, you need to submit your high school transcripts, standardized test scores (such as SAT or ACT), letters of recommendation, and a personal statement."],
    "what documents are needed for the application process?": ["The required documents for the application process typically include academic transcripts, letters of recommendation, statement of purpose, resume or CV, standardized test scores (such as GRE or GMAT), and any additional program-specific requirements. Please check the specific program's admission page for detailed information."],
    "what are the admission requirements for undergraduate programs?": ["The admission requirements for undergraduate programs vary depending on the specific program. Generally, you need to submit your high school transcripts, standardized test scores (such as SAT or ACT), letters of recommendation, and a personal statement."],
    "are there any scholarships available for international students?": ["Yes, we offer scholarships for international students. The availability and eligibility criteria of scholarships may vary. Please visit our university's scholarship page or contact the financial aid office for more information."],
    "can you provide information about the financial aid options?": ["We offer various financial aid options, including scholarships, grants, work-study programs, and loans. To learn more about the financial aid opportunities and application process, please visit our university's financial aid office or their website."],
    "is there an application fee?": ["Yes, there is an application fee for most programs. The application fee amount may vary depending on the program and level of study. Please check the specific program's admission page or contact the admissions office for the current application fee."],
    "can I transfer credits from another university?": ["Yes, you may be able to transfer credits from another university. The transfer credit policies and procedures vary, and it depends on factors such as the accreditation of the previous institution, the course comparability, and your academic performance. To know more, please contact the registrar's office or the admissions office."],
    "how can I schedule a campus tour?": ["To schedule a campus tour, you can visit our university's website and navigate to the Campus Tours or Visit Us section. There, you will find information on how to schedule a tour, available tour dates, and any registration requirements."],
    "are there any study abroad opportunities?": ["Yes, we offer study abroad opportunities for students. Our university has partnerships with various institutions around the world, providing students with the chance to study in different countries and experience new cultures. To learn more about the study abroad programs available and the application process, please visit our university's study abroad office or their website."],
   "can I get information about internship or co-op programs?": ["Certainly! Our university offers internship and co-op programs to provide students with valuable real-world work experience. These programs often allow students to apply their knowledge in professional settings and build connections in their field of study. To learn more about the internship and co-op opportunities available, please visit our university's career services office or their website."],
    "are there any sports teams that I can join?": ["Yes, our university has a variety of sports teams that students can join. We offer a range of competitive and recreational sports, including basketball, soccer, volleyball, tennis, swimming, and more. To learn about the specific sports teams and how to get involved, please contact our university's athletics department or visit their website."],
    "how can I contact the faculty of the Computer Science department?": ["To contact the faculty of the Computer Science department, you can find their contact information on our university's website. Alternatively, you can reach out to the department's administrative office, and they will assist you in connecting with the appropriate faculty members."],
    "can you provide information about the library resources?": ["Certainly! Our university library offers a vast collection of resources, including books, journals, databases, and online materials. Students have access to research assistance, study spaces, computer labs, and borrowing services. To learn more about the library resources and services, please visit our university's library website or contact the library staff."],
    "can I get information about the university's counseling services?": ["Certainly! Our university provides counseling services to support students' mental health and well-being. Our professional counselors offer individual counseling, group therapy, workshops, and resources to address various concerns such as stress, anxiety, depression, and relationship issues. To access counseling services, you can contact the university's counseling center or visit their website for more information."],
    "what are the library hours?": ["The library hours may vary depending on the day of the week and the semester. Typically, the library opens early in the morning and remains open until late evening. During exam periods, the library may have extended hours. It is recommended to check our university's library website or contact the library staff for the current operating hours."],
    "what are the university timings": ["The University opens at 9am and close at 7pm"],
    "can I get information about the university's alumni network?": ["Certainly! Our university has a strong and active alumni network. The alumni network provides opportunities for networking, mentorship, and professional development. Alumni often participate in events, career fairs, and engage in supporting current students. To learn more about our university's alumni network and how to get involved, you can visit our alumni relations office or their website."],
    "how can I access the university's online learning platform?": ["To access the university's online learning platform, you will typically need your student login credentials. Once you have your login information, you can visit the university's online platform website and log in to access your courses, assignments, lectures, and other learning materials. If you have any difficulties accessing the online learning platform, you can contact the university's IT support or the e-learning department for assistance."],
    "can I get information about the university's study spaces and libraries?": ["Certainly! Our university provides various study spaces and libraries on campus. Students can find quiet study areas, group study rooms, computer labs, and comfortable seating areas across different buildings. Additionally, we have libraries that offer extensive resources and research materials. To find specific study spaces or locate libraries, you can consult the campus map or contact the university's library services."],
    "is there a bookstore on campus?": ["Yes, we have a bookstore on campus where you can purchase textbooks, course materials, university merchandise, and supplies. The bookstore may also offer online ordering and rental options. To locate the bookstore on campus or explore online services, you can visit our university's bookstore website or contact the bookstore staff."],
    "can you provide information about the university's technology resources?": ["Certainly! Our university offers various technology resources to support students' academic and research needs. These resources may include computer labs, software applications, online databases, research tools, and Wi-Fi access across campus. To learn more about the specific technology resources available and how to access them, you can contact the university's IT department or visit their website."],
    "what is the university's policy on academic integrity?": ["Our university upholds a strict policy on academic integrity. Academic integrity is essential, and any form of plagiarism, cheating, or academic misconduct is not tolerated. The university expects students to uphold high ethical standards and maintain the integrity of their work. To familiarize yourself with the specific policies and guidelines, you can refer to the university's academic integrity policy or contact the academic affairs office."],
    "are there any tutoring services available for students?":["Certainly! Our university offers tutoring services to support students in their academic endeavors. The tutoring services are typically provided by experienced students or qualified tutors who can assist with various subjects and courses. These services may be available through dedicated tutoring centers or specific departments. To access tutoring services, you can inquire at the academic support center or contact the department offering tutoring for the subject you need assistance with."],
    "what is the process for changing majors?": ["If you wish to change your major, you will typically need to follow a specific process. This process may involve meeting with an academic advisor, submitting a formal request, and fulfilling any additional requirements set by the new department. It is recommended to contact the academic advising office or the department you wish to transfer into for detailed instructions on how to change majors."],
    "what is the university doing to promote sustainability and environmental initiatives?": ["Our university is committed to promoting sustainability and environmental initiatives on campus. There may be programs focused on energy conservation, waste reduction, recycling, green transportation, and sustainable practices. Additionally, the university may have sustainability committees, initiatives, and partnerships with local organizations to raise awareness and implement environmentally friendly practices. To get information about the university's sustainability and environmental initiatives, you can visit the sustainability office or the university's website dedicated to sustainability efforts."],
    "what is the university doing to promote campus safety and security?": ["Our university prioritizes campus safety and security and takes various measures to create a safe learning environment. These measures may include campus police or security departments, emergency preparedness programs, safety escorts, and surveillance systems. The university may also conduct safety training programs and educate students about personal safety and emergency procedures. To get information about the university's campus safety and security measures, you can visit the campus police department's website or contact them directly."],
    "what volunteer and community service opportunities are available for students": ["Our university encourages students to engage in volunteer and community service activities. There may be volunteer centers or offices that can connect students with local organizations and opportunities. These opportunities may include volunteering at nonprofit organizations, participating in community outreach programs, and engaging in service-learning projects. To explore volunteer and community service opportunities, you can contact the volunteer center or community service office, or visit their website for information on available opportunities and how to get involved."],
    "can you provide information about the university's online learning resources": ["Certainly! Our university provides online learning resources to support students in their academic pursuits. These resources may include online course materials, virtual libraries, access to online databases and journals, and interactive learning platforms. Additionally, there may be online tutoring services, discussion forums, and video conferencing tools for remote collaboration. To access online learning resources, you can visit the university's online learning platform or contact the online learning support office for assistance and information on available resources."],
    "what opportunities are there for student involvement in research projects?": ["Our university encourages student involvement in research projects across various disciplines. Students may have opportunities to work alongside faculty members on research projects, participate in undergraduate research programs, or pursue independent research under faculty mentorship. To explore opportunities for student involvement in research projects, you can reach out to faculty members in your field of interest, contact the research office, or visit the department websites for information on available research programs and initiatives."],
    "What support services are available for first-generation college students?": ["Our university understands the unique challenges faced by first-generation college students and provides support services to ensure their success. These services may include mentorship programs, academic advising tailored to first-generation students, workshops on college transition and study skills, and student organizations specifically for first-generation students. Additionally, there may be financial aid resources and scholarship opportunities available. To access support services for first-generation college students, you can contact the first-generation student services office or visit their website for detailed information and resources available."],
    "can you provide information about the university's alumni network and career connections?":["Certainly! Our university values its alumni network and recognizes the importance of connecting current students with successful alumni. The university's alumni association or career services office may facilitate networking events, mentorship programs, and alumni panels. They can provide resources for exploring career opportunities, connecting with alumni in specific industries, and accessing job listings. To get information about the university's alumni network and career connections, you can contact the alumni association or the career services office for detailed information and available resources."],
    "what support services are available for students experiencing financial hardship?": ["Our university understands that students may face financial hardships and provides support services to assist them. These services may include financial aid counseling, emergency grants or scholarships, access to food pantries or meal assistance programs, and assistance with navigating external resources such as government assistance programs. Additionally, the university may have partnerships with community organizations that provide support for students in need. To access support services for students experiencing financial hardship, you can contact the financial aid office or the student services office for detailed information and available resources."],
    "can you provide information about the university's study abroad programs?": ["Certainly! Our university offers study abroad programs that allow students to enhance their academic experience by studying in different countries. These programs may include short-term or semester-long study abroad options, language immersion programs, and cultural exchanges. The study abroad office can provide information on available programs, application procedures, eligibility requirements, and academic considerations. To get information about the university's study abroad programs, you can visit the study abroad office or their website for detailed information and available resources."],
    "can you provide information about the university's athletic programs and sports teams?": ["Certainly! Our university takes pride in its athletic programs and sports teams. We offer a variety of sports for students to participate in, such as basketball, soccer, volleyball, swimming, and track and field. We also have varsity teams that compete in intercollegiate sports. To get information about the university's athletic programs and sports teams, you can visit the athletic department's website or contact them directly for details on tryouts, game schedules, and support for student-athletes."],
    "what resources are available for students seeking mental health support?": ["Our university recognizes the importance of mental health and provides resources and support services to assist students. These resources may include counseling services, mental health workshops, support groups, and access to mental health professionals. Additionally, the university may have a dedicated counseling center or wellness center that offers a range of services to promote student well-being. To access mental health support resources, you can contact the counseling center or visit their website for detailed information and available services."],
    "what extracurricular activities and student organizations are available on campus?": ["Our university offers a wide range of extracurricular activities and student organizations to cater to diverse interests. These may include academic clubs, cultural organizations, performing arts groups, recreational clubs, and community service organizations. To explore the available extracurricular activities and student organizations, you can visit the student activities office or browse the university's website for a list of registered clubs and organizations."],
    "what support services are available for international students regarding visa and immigration matters?": ["Our university understands the unique needs of international students regarding visa and immigration matters and provides dedicated support services. These services may include immigration advising, assistance with visa applications and renewals, workshops on maintaining legal status, and guidance on employment opportunities for international students. The international student services office can provide detailed information and assistance regarding visa and immigration matters. You can contact them directly or visit their website for the available resources."],
    "what opportunities are there for students to get involved in community service and outreach programs?": ["Our university values community service and offers various opportunities for students to get involved in outreach programs. These opportunities may include volunteering with local nonprofits, participating in service-learning courses, engaging in community-based research projects, and joining student-led service organizations. To explore community service and outreach programs, you can contact the community engagement office or visit their website for information on available opportunities and how to get involved."],
    "what resources are available for students interested in studying a specific major or field?": ["Our university provides resources to support students interested in studying specific majors or fields. These resources may include academic advising specific to the major, faculty mentorship programs, research opportunities, specialized libraries or research centers, and networking events within the field. Additionally, some departments may have student organizations or clubs related to specific majors or fields. To access resources for a specific major or field of study, you can contact the respective department or visit their website for detailed information and available resources."],
    "what are the options for part-time employment for students?": ["Our university recognizes the importance of part-time employment opportunities for students. There may be various options available both on and off-campus, such as work-study programs, internships, research assistantships, and part-time jobs in local businesses. To explore part-time employment options for students, you can visit the university's career services office, job boards, or online platforms dedicated to student employment."],
    "what are the options for campus transportation?": ["Our university provides various options for campus transportation to help students navigate the campus conveniently. These options may include shuttle services, bike-sharing programs, designated parking areas, and pedestrian-friendly pathways. To get information about the campus transportation options, you can visit the transportation services office or the university's website for details on routes, schedules, and any associated fees or permits."],
    "what resources are available for students with disabilities or special needs?": ["Our university is committed to providing support and resources for students with disabilities or special needs. These resources may include disability services offices, accommodations for academic and living environments, assistive technology, accessible transportation, and support in navigating campus facilities. Additionally, there may be disability-related student organizations and advocacy groups. To access resources for students with disabilities or special needs, you can contact the disability services office or visit their website for detailed information and available resources."],
    "what career counseling and job placement services are available for students?": ["Our university offers career counseling and job placement services to assist students in their career development and job search. These services may include resume and cover letter reviews, career assessments, interview preparation, job search strategies, and networking events. Additionally, the university may have partnerships with employers and host career fairs or job recruitment events. To access career counseling and job placement services, you can contact the career services office or visit their website for detailed information and available resources."],
    "what resources are available for students interested in studying abroad?": ["Our university provides resources for students interested in studying abroad. These resources may include information on available study abroad programs, application procedures, scholarships and funding opportunities, and guidance on academic considerations. The study abroad office can provide detailed information and support for students who wish to explore studying abroad. You can contact them directly or visit their website for the available resources."],
    "are there opportunities for students to get involved in undergraduate research projects?": ["Certainly! Our university encourages student involvement in undergraduate research projects. Opportunities may exist for students to work alongside faculty members on research initiatives, participate in research programs or internships, and present their findings at conferences or symposiums. To explore opportunities for undergraduate research projects, you can reach out to faculty members in your field of interest, contact the undergraduate research office, or visit the department websites for information on available research programs and initiatives."],
    "what support services are available for students with mental health concerns?": ["Our university prioritizes the mental health and well-being of its students and provides support services for students with mental health concerns. These services may include counseling and therapy services, mental health workshops and programs, crisis intervention, and referrals to external resources. Additionally, there may be peer support groups and mental health awareness campaigns on campus. To access support services for mental health concerns, you can contact the counseling center or mental health services office for detailed information and available resources."],
    "can you provide information about the university's internship and co-op programs?": ["Certainly! Our university offers internship and co-op programs that provide valuable hands-on experience for students in their field of study. These programs may include opportunities to work with local businesses, organizations, or government agencies to gain practical skills and apply classroom knowledge. The career services office or the department offering your major can provide information on available internship and co-op programs, application procedures, and eligibility requirements. You can also visit their respective websites for detailed information and available resources."],
    "what recreational facilities are available for students on campus?": ["Our university offers a variety of recreational facilities to promote an active and healthy lifestyle among students. These facilities may include a fitness center, swimming pool, sports fields, indoor and outdoor courts, and walking trails. Additionally, there may be group fitness classes, intramural sports leagues, and outdoor adventure programs. To explore the recreational facilities available on campus, you can contact the campus recreation center or visit their website for detailed information and available resources."],
   "what tutoring services are available to students who need academic assistance?": ["Our university provides tutoring services to assist students who need academic assistance. These services may include peer tutoring, group study sessions, writing centers for assistance with writing assignments, and subject-specific tutoring for challenging courses. The academic support center or the tutoring center can provide detailed information on available tutoring services, scheduling appointments, and resources to enhance your academic performance."],
    "what academic advising services are available to help students with course selection and degree planning?": ["Our university provides academic advising services to assist students with course selection, degree planning, and academic progress. Academic advisors can help you navigate degree requirements, explore major options, plan your course schedule, and ensure you are on track to meet graduation requirements. To access academic advising services, you can contact the academic advising office or the department offering your major for appointments and guidance."],
    "what support services are available for students with learning disabilities or neurodivergent conditions?": ["Our university provides support services for students with learning disabilities or neurodivergent conditions. These services may include academic accommodations, assistive technologies, specialized tutoring, and accessibility resources. The disability services office can provide detailed information on the available support services, documentation requirements, and the process to request accommodations."],
    "what resources are available for students interested in joining or starting a student club or organization?": ["Our university supports student clubs and organizations as they play a vital role in campus life. There may be resources available to assist students in joining or starting a club. These resources may include information on the club registration process, funding opportunities, meeting spaces, and leadership development programs. The student activities office or the student affairs department can provide detailed information on how to get involved in student clubs and organizations."],
    "what opportunities are available for students to engage in undergraduate research or creative projects?": ["Our university values undergraduate research and creative projects as valuable learning experiences. Opportunities may exist for students to collaborate with faculty members on research or creative initiatives, present their work at conferences or exhibitions, and publish their findings. The undergraduate research office or the department offering your major can provide information on available research opportunities, funding options, and guidelines for getting involved."]
    
}

# Define a function to generate a response to the user input
def generate_response(user_input):
    # Convert the user input to lowercase and remove any punctuation
    cleaned_input = user_input.lower().strip("?.,!")
    # Check if the cleaned input is in the input_responses dictionary
    if cleaned_input in input_responses:
        # If it is, select a random response from the list of responses for that input
        response = random.choice(input_responses[cleaned_input])
    else:
        # If it's not, provide a generic response
        response = "I'm sorry, I didn't understand your question."
    return response

# Main loop for the chatbot
while True:
    # Prompt the user for input
    user_input = input("You: ")
    # Generate a response to the user input
    bot_response = generate_response(user_input)
    # Print the bot's response
    print("ChatBot:", bot_response)
